language: python
sudo: false

branches:
  only:
    - master

python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - pypy

env:
  - SERIALIZATION_PKG="marshmallow==2.15.1"
  - SERIALIZATION_PKG="marshmallow==3.2.0"
  - SERIALIZATION_PKG="schematics==2.1.0"

matrix:
  exclude:
    # Python 2.7 (and pypy) are not supported in Marshmallow 3+
    - python: 2.7
      env: SERIALIZATION_PKG="marshmallow==3.2.0"
    - python: pypy
      env: SERIALIZATION_PKG="marshmallow==3.2.0"

install: false
script: ./build.sh
after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: pypi
  user: __token__
  password:
    secure: "C0hRA/TnDOxMQyCUngaoUVp4PGVfPhIeh8Yr6sFa2XN+y0/afJVXBzbz2zrzXflg93zsZIppNTS+sUuYauae/v8ZRqvU1pjS5xVdlZytMBRt53omej2pe+m4DPe8RADIy5fkfuEyt9F1j7ZKXnxwXI+kz1x6cXShM09pCtCuvc26vTNQN3HycUeA11Fp3Bir4CGMx1qKE6hWwzM1+TP2Ci9Vp4mgAh6oqwpfKYIKtbJRd9Uy5r8RPmfc2suaau5S4kCKjqSGvrcbAOjpTTl6TZoTTpJstPnXb46kDwRaAWC34CRrgK3f0dgfyTm2OKgRMCrhR4JiZp016YvcADKySTtQOlyYn+x9jbV4j0USP8yebJLtPrWX124JAy1Y4tnCXsW7E3Uh7yK1pm3DO1WquHgT3qwUcsL6NCaoGCt9NwzunV0jTTRAVr43zpxkBaD73Vejv3gHaLpMrwccqywFZEjjUh0qJLk3qBIAWefV3aKhPoefRqFRN56BZFbcr0KZTCjZfFGUjno6ncblHqNbYd365SC95dt+FOh9GP7gkHX3l+R9F/eGxfyubPrZLrZSn01y0gSQFLEFHIyYzVofq8p0OZN6ZB/lebOE3r3SHrfiUJF5hoGCyCrqERCCiO2fjn8WmR+n1MLTmdafVlMCnm+FMq1d7pcodK8QDjYk6vo="
  on:
    branch: master
    python: 3.7
    condition: $SERIALIZATION_PKG = schematics==2.1.0
  distributions: "sdist bdist_wheel"
