language: python
sudo: false

python:
  - 2.6
  - 2.7
  - 3.4
  - 3.5
  - pypy

env:
  - SERIALIZATION_PKG="marshmallow==2.7.0"
  - SERIALIZATION_PKG="schematics==1.0.4"

install:
  - pip install -e .
  - pip install codecov pytest travis-sphinx
  - pip install $SERIALIZATION_PKG

script:
  - coverage run --source=dynamallow setup.py test
  - travis-sphinx --source=docs/ build

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - travis-sphinx deploy
